### ISSUE TITLE
Rename repository with `-` instead of `_`

### ISSUE THREAD

**Issue by gytis-ivaskevicius** [wiktoraleksanderkaczor/honours_approaches#2]

**Comment by wiktoraleksanderkaczor** [comment]
Give me a commands to do it, update it locally I mean. @gytis-ivaskevicius

**Comment by gytis-ivaskevicius** [comment]
i have no idea how github cli works, just go to repository settings

**Comment by wiktoraleksanderkaczor** [comment]
Yeah, I think it looks better the way it is...
